version: "3"
services:
  db:
    image: postgres:12.8
    user: postgres
    environment:
      - POSTGRES_USER=parallel
      - POSTGRES_PASSWORD=lellarap
      - POSTGRES_DB=parallel_dev
    ports:
      - "5432:5432"
    volumes:
      - $HOME/docker/volumes/parallel/postgres:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - $HOME/docker/volumes/parallel/redis:/var/lib/redis
    command: redis-server
  nginx:
    image: nginx:latest
    volumes:
      - $HOME/docker/volumes/parallel/nginx:/var/cache/nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.maintenance.conf:/etc/nginx/nginx.maintenance.conf
    ports:
      - 80:80
      - 443:443
  queue:
    image: softwaremill/elasticmq:latest
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf
    ports:
      - "9324:9324"
