version: "3"
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=parallel
      - POSTGRES_PASSWORD=lellarap
      - POSTGRES_DB=parallel_dev
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - $HOME/docker/volumes/parallel/redis:/var/lib/redis
    command: redis-server
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
  queue:
    image: softwaremill/elasticmq
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf
    ports:
      - "9324:9324"
  parallel_client:
    build:
      context: ./../../
      dockerfile: client/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - nginx
      - parallel_server
    environment:
      - PARALLEL_SERVER_HOST=parallel_server
  parallel_server:
    build:
      context: ./../../
      dockerfile: server/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
    depends_on:
      - db
      - redis
      - queue
  testing:
    build:
      context: ./../../
      dockerfile: e2e/Dockerfile
    depends_on:
      - parallel_client
      - parallel_server
    environment:
      - PARALLEL_CLIENT_HOST=parallel_client
      - PARALLEL_CLIENT_PORT=3000
      - PARALLEL_SERVER_HOST=parallel_server
      - PLAYWRIGHT_HEADLESS=true
      - DEBUG=pw:api
